#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    FZF_DEFAULT_OPTS="--color=bg+:-1,bg:-1,spinner:#7fa563,hl:#f3be7c \
    --color=fg:#cdcdcd,header:#6e94b2,info:#f3be7c,pointer:#aeaed1 \
    --color=marker:#d8647e,fg+:#bebeda,prompt:#bb9dbd,hl+:#f3be7c"
    selected=$(find ~/things ~/.config -mindepth 1 -maxdepth 1 \( -type d -o -type l \) | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux attach -t $selected_name
else
    tmux switch-client -t $selected_name
fi
